version: "3"

services:
  odoo:
    image: jakkph32/mts-odoo:latest
    container_name: odoo
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRESS_DB=${PGDATABASE}
    ports:
      - 8069:8069
      - 8072:8072
    volumes:
      - ./addons:/mnt/extra-addons